-- The jobs table is both the durable record of every job and the queue itself.
-- There is no second system: PostgreSQL is the source of truth.

-- ---------------------------------------------------------------------------
-- updated_at trigger
-- ---------------------------------------------------------------------------
-- Maintaining updated_at in the database rather than in application code means
-- it is correct even for an UPDATE issued from psql during an incident.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- jobs
-- ---------------------------------------------------------------------------
CREATE TABLE jobs (
    -- Generated by the API in Go rather than by the database, so the id can be
    -- logged and returned even if the INSERT itself has to be retried.
    id UUID PRIMARY KEY,

    -- Routed to a handler by the worker's registry.
    type TEXT NOT NULL
        CONSTRAINT jobs_type_length CHECK (char_length(type) BETWEEN 1 AND 100),

    -- JSONB, not JSON: stored decomposed and binary, so it is queryable and
    -- cheap to read. Large payloads belong in object storage with a pointer
    -- here; the API caps the request body to keep that honest.
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,

    -- TEXT + CHECK rather than a native ENUM. A native enum is 4 bytes and
    -- validates at the type level, but ALTER TYPE ... ADD VALUE is awkward
    -- inside a migration transaction and enum value order is baked in. Status
    -- appears in index *predicates*, not index keys, so the storage saving
    -- would not buy us anything here.
    status TEXT NOT NULL DEFAULT 'pending'
        CONSTRAINT jobs_status_valid CHECK (
            status IN ('pending', 'running', 'completed', 'dead_letter', 'cancelled')
        ),

    -- Higher runs sooner. SMALLINT is plenty for 1..100.
    priority SMALLINT NOT NULL DEFAULT 50
        CONSTRAINT jobs_priority_range CHECK (priority BETWEEN 1 AND 100),

    -- Number of attempts that have already been made.
    attempts INT NOT NULL DEFAULT 0
        CONSTRAINT jobs_attempts_non_negative CHECK (attempts >= 0),

    max_retries INT NOT NULL DEFAULT 3
        CONSTRAINT jobs_max_retries_range CHECK (max_retries BETWEEN 0 AND 100),

    -- USER INTENT. Set once at creation, never mutated. NULL means "run ASAP".
    scheduled_at TIMESTAMPTZ,

    -- SYSTEM ELIGIBILITY. Initialised to COALESCE(scheduled_at, now()) and
    -- overwritten on every retry with the backoff deadline. The claim query
    -- reads THIS column and never scheduled_at.
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    started_at   TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    failed_at    TIMESTAMPTZ,

    -- Visibility timeout. A worker owns a job only until this instant.
    lease_until TIMESTAMPTZ,

    -- Fencing token, incremented on every claim. A worker that was frozen past
    -- its lease expiry and wakes up holding a stale epoch will match zero rows
    -- when it tries to write, instead of clobbering the new owner's work.
    lease_epoch BIGINT NOT NULL DEFAULT 0
        CONSTRAINT jobs_lease_epoch_non_negative CHECK (lease_epoch >= 0),

    worker_id TEXT,

    idempotency_key TEXT
        CONSTRAINT jobs_idempotency_key_length CHECK (
            idempotency_key IS NULL OR char_length(idempotency_key) BETWEEN 1 AND 255
        ),

    -- Truncated by the application. Must never contain the payload.
    last_error TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- A running job always has an owner and a deadline. This turns "a worker
    -- forgot to set the lease" from a silent stuck job into a failed write.
    CONSTRAINT jobs_running_has_lease CHECK (
        status <> 'running' OR (lease_until IS NOT NULL AND worker_id IS NOT NULL)
    ),

    -- Retries can never exceed the configured budget.
    CONSTRAINT jobs_attempts_within_budget CHECK (attempts <= max_retries + 1)
);

CREATE TRIGGER jobs_set_updated_at
    BEFORE UPDATE ON jobs
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- 1. THE CLAIM INDEX. Every worker poll uses exactly this ordering:
--
--      SELECT ... FROM jobs
--       WHERE status = 'pending' AND available_at <= now()
--       ORDER BY priority DESC, available_at ASC, id ASC
--       FOR UPDATE SKIP LOCKED LIMIT $1
--
--    PARTIAL (WHERE status = 'pending'): a healthy queue holds millions of
--    completed rows and a handful of pending ones. A full index would be
--    almost entirely dead weight competing for cache; this one stays small and
--    hot, and rows leave it the moment a job completes.
--
--    COLUMN ORDER MIRRORS THE ORDER BY so Postgres walks the index in order and
--    never sorts. Without that, SKIP LOCKED hands out jobs in arbitrary order
--    and the priority feature is decorative.
--
--    id LAST makes the ordering total, which makes concurrency tests
--    deterministic and assertable.
CREATE INDEX jobs_claim_idx
    ON jobs (priority DESC, available_at ASC, id ASC)
    WHERE status = 'pending';

-- 2. LEASE RECOVERY. The reaper runs
--      WHERE status = 'running' AND lease_until < now()
--    Running jobs are a tiny fraction of the table, so a partial index turns
--    this from a sequential scan into a narrow range scan.
CREATE INDEX jobs_lease_expiry_idx
    ON jobs (lease_until)
    WHERE status = 'running';

-- 3. IDEMPOTENCY. Partial-unique so the many NULL-key jobs neither collide nor
--    bloat the index. This constraint - not an application-level SELECT - is
--    what actually prevents duplicate jobs under concurrency.
CREATE UNIQUE INDEX jobs_idempotency_key_idx
    ON jobs (idempotency_key)
    WHERE idempotency_key IS NOT NULL;

-- Deliberately NOT indexed yet: type, worker_id, and no GIN on payload. Each
-- costs write amplification on the hottest table in the system and is
-- justified only by a query that exists. List-endpoint indexes are added in a
-- later migration, after EXPLAIN ANALYZE shows they are needed.

COMMENT ON TABLE  jobs                 IS 'Durable job queue. PostgreSQL is the source of truth.';
COMMENT ON COLUMN jobs.scheduled_at    IS 'User intent. Immutable after creation.';
COMMENT ON COLUMN jobs.available_at    IS 'System eligibility. Mutated by retry backoff. The claim query reads this.';
COMMENT ON COLUMN jobs.lease_until     IS 'Visibility timeout. After this instant the job may be reclaimed.';
COMMENT ON COLUMN jobs.lease_epoch     IS 'Fencing token incremented on every claim.';
